Add unique css handle to each stack item
vtex-apps/stack-layout pull request #5
Opened 2020-01-29 20:07 UTC by Klynger

With the current behavior, there is no way to position each element in the stack, with this handle you can do it now.

See the preview button in this [workspace](https://quickview--storecomponents.myvtex.com/)

![image](https://user-images.githubusercontent.com/8517023/73393030-b87ffd00-42b9-11ea-90df-f3e39ca1db81.png)

2020-01-29 20:27 UTC, victorhmp requested changes

2020-01-29 20:27 UTC, victorhmp commented on react/index.tsx
> +const CSS_HANDLES = ['stackContainer', 'stackItem', 'item'] as const
```suggestion
const CSS_HANDLES = ['stackContainer', 'stackItem'] as const
```

2020-01-29 23:52 UTC, victorhmp approved these changes

2020-01-30 13:20 UTC, iaronaraujo approved these changes

2020-01-30 14:18 UTC, klzns approved these changes

2020-01-30 18:36 UTC, lbebber reviewed
umas sugestoezinhas, mas parece bom

acho que isso tb requer atualizar documentaçao

2020-01-30 18:36 UTC, lbebber commented on react/index.tsx
> +        let stackItemExtraBlockClass = ''
⛏ acho q da pra tirar o "extra" do nome

2020-01-30 18:36 UTC, lbebber commented on react/index.tsx
> +        const childBlockClass = (child as any)?.props?.blockProps?.blockClass ? (child as any).props.blockProps.blockClass : ''
⛏ isso nao rola talvez? (nunca usei o `?`, nao tenho certeza):

`(child as any)?.props?.blockProps?.blockClass || '')`

2020-01-30 18:36 UTC, lbebber commented on react/index.tsx
> +        const childBlockClass = (child as any)?.props?.blockProps?.blockClass ? (child as any).props.blockProps.blockClass : ''
```suggestion
        // This allows the user customize the stackItem via CSS, via the blockClass of each child
        const childBlockClass = (child as any)?.props?.blockProps?.blockClass ? (child as any).props.blockProps.blockClass : ''
```

2020-01-30 18:43 UTC, lbebber approved these changes

2020-01-30 18:59 UTC, merged